name: Generate github pages

on:
  push:
    branches:
      - 'reference-expansion'
  workflow_dispatch:

env:
  MDBOOK_VERSION: 0.4.52

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout rust-lang/rust
      uses: actions/checkout@master
      with:
        repository: rust-lang/rust
        path: rust
    - name: Update rustup
      run: rustup self update
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install nightly -c rust-docs,rustfmt
        rustup default nightly
    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> $GITHUB_PATH
    - name: Report versions
      run: |
        rustup --version
        rustc -Vv
        mdbook --version
    - name: Verify the book builds
      env:
        SPEC_RUST_ROOT: ${{ github.workspace }}/rust
      run: mdbook build
    - name: Update pages artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: book/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${\{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
